# Generated by Django 6.0.4 on 2026-07-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0004_department_studentid_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="department",
        ),
        migrations.RemoveField(
            model_name="student",
            name="student_id",
        ),
        migrations.AlterModelOptions(
            name="department",
            options={},
        ),
        migrations.AlterField(
            model_name="department",
            name="department_code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name="Receipe",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="StudentID",
        ),
    ]
