# Generated by Django 6.0.4 on 2026-06-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_studnets_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studnets',
            name='file',
        ),
        migrations.RemoveField(
            model_name='studnets',
            name='image',
        ),
    ]
