# Generated by Django 6.0.4 on 2026-06-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_studnets_file_remove_studnets_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studnets',
            new_name='Students',
        ),
    ]
