# Generated by Django 6.0.4 on 2026-06-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_students_age_alter_students_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=500)),
                ("car_speed", models.IntegerField(default=50, max_length=500)),
            ],
        ),
    ]
