# Generated by Django 6.0.4 on 2026-06-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_speed",
            field=models.IntegerField(default=50),
        ),
    ]
